import React from "react";
import { useEffect } from "react";
import Icon_Box from "../../Component/Icons_Box/Icon_Box";
import "../../Pages/Provides/Provide.css";

function Provide() {
  return (
    <div className="provide-main">
      <div className="provider-class">
        <img src="provide.jpg" alt="" id="provide-img" />
        <div className="text-res">
          <p>WHAT WE DO?</p>
          <h1 id="res-h1">PROVIDING ENERGY TO THE WORLD</h1>
          <p id="res-h2">
            Our four strategic pillars solar,wind,hydo and new energy – each
            have a role to play.
          </p>
        </div>
        <h1 className="plants"> <i>HYDRO</i> PLANTS AND PROJECTS</h1>
        <div className="water_plant">
          <Icon_Box
            image="Hydro-bhira.jpg"
            width="700px"
            height="400px"
            text_color="black"
            // title="Hydro-Plant"
            margin="0px 0px 40px 50px"
            display="flex"
            text="Location - Andhra Predesh
            Plant Size - 100 MW
            Type - Epic utility sacle ground mount solar project
            Project Completion date - 3 months ahead of schedule
            Land area - 500 acres
            CO2 offset - 110,000 tones annualy
            Annualy energy yeild - 160 million units (kwh)"
          />
          <Icon_Box
            width="700px"
            height="400px"
            display="flex"
            text_color="black"
            margin="0px 0px 40px 80px"
            image="Hydro-itezhi.jpg"
            text="Location - Andhra Predesh
            Plant Size - 100 MW
            Type - Epic utility sacle ground mount solar project
            Project Completion date - 3 months ahead of schedule
            Land area - 500 acres
            CO2 offset - 110,000 tones annualy
            Annualy energy yeild - 160 million units (kwh)"

          />
        </div>
        <h1 className="plants"><i>AIR</i> PLANTS AND PROJECTS</h1>
        <div className="wind_plant">
          <Icon_Box
            width="700px"
            height="400px"
            text_color="black"
            image="business-overview-pic1.jpg"
            margin="0px 0px 50px 50px"
            display="flex"
            text="Location - Bhira, MaharashtraPlant Size - 300 MWType - Hydro GenerationCompleted in 1927, the hydro plant's maximum output capacity is nominally 300 MW, generated by six 25 MW Pelton turbines and a 150 MW pumped storage generator"
          />
          <Icon_Box
            width="700px"
            height="400px"
            text_color="black"
            image="business-overview-pic1.jpg"
            margin="0px 0px 40px 80px"
            display="flex"
            text="Location - Bhira, MaharashtraPlant Size - 300 MWType - Hydro GenerationCompleted in 1927, the hydro plant's maximum output capacity is nominally 300 MW, generated by six 25 MW Pelton turbines and a 150 MW pumped storage generator"
          />
        </div>
        <h1 className="plants"><i>SOLAR</i> PLANTS AND PROJECTS</h1>
        <div className="solar_plant">
          <Icon_Box
            width="700px"
            height="400px"
            text_color="black"
            image="solar-img.jpg"
            img_width="350px"
            margin="0px 0px 40px 50px"
            display="flex"
            text="Location - Bhira, MaharashtraPlant Size - 300 MWType - Hydro GenerationCompleted in 1927, the hydro plant's maximum output capacity is nominally 300 MW, generated by six 25 MW Pelton turbines and a 150 MW pumped storage generator"
          />
          <Icon_Box
            width="700px"
            height="400px"
            text_color="black"
            image="solar.jpg"
            img_width="350px"
            margin="0px 0px 40px 80px"
            display="flex"
            text="Location - Bhira, MaharashtraPlant Size - 300 MWType - Hydro GenerationCompleted in 1927, the hydro plant's maximum output capacity is nominally 300 MW, generated by six 25 MW Pelton turbines and a 150 MW pumped storage generator"
          />
        </div>
          {/* <h1 className="plants"><i>GEO</i> PLANTS AND PROJECTS</h1>
        <div className="thermal_plant">
          <Icon_Box
            width="700px"
            height="400px"
            margin="0px 0px 40px 5px"
            display="flex"
          />
          <Icon_Box
            width="700px"
            height="400px"
            margin="0px 0px 40px 80px"
            display="flex"
          />
          <Icon_Box
            width="700px"
            height="400px"
            margin="0px 0px 40px 80px"
            display="flex"
          />
          
        </div> */}
      </div>
    </div>
  );
}

export default Provide;
